create: obscure.cpp circleObj.o rectObj.o
	g++ circleObj.h -o circleObj.o
	g++ rectObj.h -o rectObj.o
	g++ obscure.cpp -o obscure
clean:
	rm obscure
	rm rectObj.o
	rm circleObj.o
	rm rectData.txt
	rm angleObscureTotal.txt
run:
	./obscure
